// Business enums shared by every service. Values are what is stored in Google Sheets.

export const RECORD_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
});

export const INVENTORY_MODE = Object.freeze({
  COLOR_WISE: 'COLOR_WISE',
  BOX_WISE: 'BOX_WISE',
});

export const INVENTORY_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
});

export const DISCOUNT_MODE = Object.freeze({
  FIXED: 'FIXED',
  SLAB: 'SLAB',
});

// Product level: follow the global discount (fixed or slab) or use its own fixed %
export const PRODUCT_DISCOUNT_MODE = Object.freeze({
  GLOBAL: 'GLOBAL',
  CUSTOM: 'CUSTOM',
});

export const SLAB_BASIS = Object.freeze({
  MRP_SUBTOTAL: 'MRP_SUBTOTAL',
  PRE_DISCOUNT_WHOLESALE_SUBTOTAL: 'PRE_DISCOUNT_WHOLESALE_SUBTOTAL',
  FINAL_PAYABLE: 'FINAL_PAYABLE',
});

export const PRICE_DISPLAY_MODE = Object.freeze({
  SHOW_MRP: 'SHOW_MRP',
  SHOW_WHOLESALE: 'SHOW_WHOLESALE',
  SHOW_BOTH: 'SHOW_BOTH',
});

// How an order is paid: ONLINE = UPI QR step after checkout; OFFLINE = online
// payment was switched off, the team confirms the order (blank = ONLINE).
export const PAYMENT_MODE = Object.freeze({ ONLINE: 'ONLINE', OFFLINE: 'OFFLINE' });

export const ORDER_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUBMITTED: 'PAYMENT_SUBMITTED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  DISPATCHED: 'DISPATCHED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

// Tracks what an order is currently doing to inventory, so every stock
// transition is applied exactly once.
export const STOCK_STATE = Object.freeze({
  RESERVED: 'RESERVED', // held by an unpaid (editable) order
  DEDUCTED: 'DEDUCTED', // committed after payment submission
  RELEASED: 'RELEASED', // returned to stock (order cancelled)
});

export const IMAGE_TYPE = Object.freeze({
  MAIN: 'MAIN',
  GALLERY: 'GALLERY',
  THUMBNAIL: 'THUMBNAIL',
});

export const ITEM_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  REPLACED: 'REPLACED', // superseded by a customer edit; kept for history
});

export const ACTOR = Object.freeze({
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  SYSTEM: 'SYSTEM',
});

export const ADMIN_ROLE = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
});

export const AUDIT_ACTION = Object.freeze({
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DUPLICATED: 'PRODUCT_DUPLICATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  PRODUCT_REACTIVATED: 'PRODUCT_REACTIVATED',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_STOCK_RESTORED: 'PRODUCT_STOCK_RESTORED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DEACTIVATED: 'CATEGORY_DEACTIVATED',
  CATEGORY_REACTIVATED: 'CATEGORY_REACTIVATED',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  COLOR_CREATED: 'COLOR_CREATED',
  COLOR_UPDATED: 'COLOR_UPDATED',
  COLOR_DEACTIVATED: 'COLOR_DEACTIVATED',
  COLOR_REACTIVATED: 'COLOR_REACTIVATED',
  SIZE_CREATED: 'SIZE_CREATED',
  SIZE_UPDATED: 'SIZE_UPDATED',
  SIZE_DEACTIVATED: 'SIZE_DEACTIVATED',
  SIZE_REACTIVATED: 'SIZE_REACTIVATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  PRICE_UPDATED: 'PRICE_UPDATED',
  DISCOUNT_UPDATED: 'DISCOUNT_UPDATED',
  SLAB_CREATED: 'SLAB_CREATED',
  SLAB_UPDATED: 'SLAB_UPDATED',
  SLAB_DEACTIVATED: 'SLAB_DEACTIVATED',
  SLAB_REACTIVATED: 'SLAB_REACTIVATED',
  SLAB_DELETED: 'SLAB_DELETED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED_BY_CUSTOMER: 'ORDER_UPDATED_BY_CUSTOMER',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_REOPENED: 'ORDER_REOPENED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_AUTO_CANCELLED: 'ORDER_AUTO_CANCELLED',
  PAYMENT_SUBMITTED: 'PAYMENT_SUBMITTED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  MASTER_DATA_INITIALIZED: 'MASTER_DATA_INITIALIZED',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_PASSWORD_CHANGED: 'ADMIN_PASSWORD_CHANGED',
  DATA_EXPORTED: 'DATA_EXPORTED',
  EXISTING_CUSTOMER_ADDED: 'EXISTING_CUSTOMER_ADDED',
  EXISTING_CUSTOMER_UPDATED: 'EXISTING_CUSTOMER_UPDATED',
  EXISTING_CUSTOMER_DEACTIVATED: 'EXISTING_CUSTOMER_DEACTIVATED',
  EXISTING_CUSTOMER_REACTIVATED: 'EXISTING_CUSTOMER_REACTIVATED',
  EXISTING_CUSTOMER_VERIFIED: 'EXISTING_CUSTOMER_VERIFIED',
  CATALOG_IMPORTED: 'CATALOG_IMPORTED',
});

export const CUSTOMER_TYPE = Object.freeze({
  NEW: 'NEW',
  EXISTING: 'EXISTING',
});

export const DRIVE_FOLDERS = Object.freeze({
  PRODUCTS: 'PRODUCTS',
  CATEGORIES: 'CATEGORIES',
  COLORS: 'COLORS',
  PAYMENT: 'PAYMENT',
  PAYMENT_PROOFS: 'PAYMENT-PROOFS',
  BRAND: 'BRAND',
});

export const TIMEZONE = 'Asia/Kolkata';
