import { useState } from 'react';
import { Copy, Check, TriangleAlert } from 'lucide-react';
import { formatINR } from '../../utils/format.js';

/**
 * Displays EXACTLY the QR image uploaded by the admin (served from Google
 * Drive). No payment QR is generated by the website.
 * Until a real QR is uploaded, a clearly-labelled SAMPLE QR is shown so the
 * page can be previewed; it contains only text and cannot receive payments.
 */
export function PaymentQR({ settings, amount, orderNumber }) {
  const [copied, setCopied] = useState(false);
  const isDemo = !settings?.payment_qr_url;
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(settings.upi_id);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable (needs https) */
    }
  };
  return (
    <div className="qr-box">
      <div>
        <div className="small muted">Amount to pay for order <strong>{orderNumber}</strong></div>
        <div className="amount-due num">{formatINR(amount)}</div>
      </div>
      {isDemo ? (
        <>
          <div className="qr-demo-wrap">
            <img className="qr-img" src={settings?.payment_qr_demo_url || '/media/demo-payment-qr.png'} alt="Sample QR code - not for payment" />
            <span className="qr-demo-ribbon">DEMO QR</span>
          </div>
          <div className="alert alert-warning" style={{ textAlign: 'left' }}>
            <TriangleAlert />
            <div><strong>Sample QR - do not pay.</strong> This only shows how the payment page works. The company's real UPI QR code will appear here once it is uploaded. Please contact us on WhatsApp for payment details.</div>
          </div>
        </>
      ) : (
        <img className="qr-img" src={settings.payment_qr_url} alt={`Payment QR code for ${settings.payment_name || settings.company_name}`} />
      )}
      {settings?.payment_name && <div className="small">Payee: <strong>{settings.payment_name}</strong></div>}
      {settings?.upi_id && !isDemo && (
        <div className="upi-row">
          <span className="small muted">UPI ID</span>
          <code>{settings.upi_id}</code>
          <button type="button" className="btn btn-sm btn-dark" onClick={copy}>{copied ? <><Check /> Copied</> : <><Copy /> Copy</>}</button>
        </div>
      )}
    </div>
  );
}
