import { useEffect, useState } from 'react';
import { Copy, Check, TriangleAlert } from 'lucide-react';
import { formatINR } from '../../utils/format.js';
import { cachedQrCrop, findQrCrop } from '../../utils/qrCrop.js';

/**
 * Displays EXACTLY the QR image uploaded by the admin (served from Google
 * Drive). No payment QR is generated by the website.
 * Until a real QR is uploaded, a clearly-labelled SAMPLE QR is shown so the
 * page can be previewed; it contains only text and cannot receive payments.
 * The uploaded image is shown in full (as the admin uploaded it); when it is a
 * whole standee/poster, "Zoom in on the QR code" shows just the QR square.
 */
export function PaymentQR({ settings, amount, orderNumber }) {
  const [copied, setCopied] = useState(false);
  const isDemo = !settings?.payment_qr_url;
  const src = settings?.payment_qr_url || '';
  const [crop, setCrop] = useState(() => cachedQrCrop(src));
  const [showFull, setShowFull] = useState(true);
  useEffect(() => {
    if (!src) return undefined;
    let alive = true;
    findQrCrop(src).then((c) => { if (alive) setCrop(c); }).catch(() => { /* show the full image */ });
    return () => { alive = false; };
  }, [src]);
  // UPI ID from Settings, else the one inside the QR (cropped out of the poster)
  const upiId = settings?.upi_id || crop?.upi || '';
  const alt = `Payment QR code for ${settings?.payment_name || settings?.company_name || 'Nutex'}`;
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(upiId);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable (needs https) */
    }
  };
  return (
    <div className="qr-box">
      <div>
        <div className="small muted">Amount to pay for order <strong>{orderNumber}</strong></div>
        <div className="amount-due num">{formatINR(amount)}</div>
      </div>
      {isDemo ? (
        <>
          <div className="qr-demo-wrap">
            <img className="qr-img" src={settings?.payment_qr_demo_url || '/media/demo-payment-qr.png'} alt="Sample QR code - not for payment" />
            <span className="qr-demo-ribbon">DEMO QR</span>
          </div>
          <div className="alert alert-warning" style={{ textAlign: 'left' }}>
            <TriangleAlert />
            <div><strong>Sample QR - do not pay.</strong> This only shows how the payment page works. The company's real UPI QR code will appear here once it is uploaded. Please contact us on WhatsApp for payment details.</div>
          </div>
        </>
      ) : (
        <>
          {crop && !showFull ? (
            <div className="qr-frame">
              <div className="qr-crop">
                <img
                  src={src}
                  alt={alt}
                  style={{ width: `${(crop.iw / crop.side) * 100}%`, left: `${(-crop.x / crop.side) * 100}%`, top: `${(-crop.y / crop.side) * 100}%` }}
                />
              </div>
            </div>
          ) : (
            <img className="qr-img qr-img-full" src={src} alt={alt} />
          )}
          {crop && (
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => setShowFull((v) => !v)}>
              {showFull ? 'Zoom in on the QR code' : 'Show the full QR image'}
            </button>
          )}
        </>
      )}
      {settings?.payment_name && <div className="small">Payee: <strong>{settings.payment_name}</strong></div>}
      {upiId && !isDemo && (
        <div className="upi-row">
          <span className="small muted">UPI ID</span>
          <code>{upiId}</code>
          <button type="button" className="btn btn-sm btn-dark" onClick={copy}>{copied ? <><Check /> Copied</> : <><Copy /> Copy</>}</button>
        </div>
      )}
    </div>
  );
}
